# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7003
  connection-timeout: 5000ms
  servlet:
    context-path: /shard-jdbc

spring:
  application:
    name: shard-jdbc
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/shard_one
    user: root
    password: 123456
  mvc:
    throw-exception-if-no-handler-found: true

# mybatis
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml